### ISSUE TITLE
handle passkey creation error

### ISSUE THREAD

**Issue by cstrnt** [uninbox/UnInbox#29]
I've tried creating an account in firefox where I don't have any passkey setup.
Therefore the setup failed and an error was logged to the console but the UI still displayed a loading state.

Optimally there should be a toast giving some feedback to the user

**Comment by McPizza0** [comment]
can you share the console error so I can try to diagnose?
also seeing some errors in firefox, need to create a workaround

**Comment by McPizza0** [comment]
on macOS, when clicking "Create my account"
i get:
![image](https://github.com/uninbox/UnInbox/assets/17185737/923e3e20-7725-46c1-90bd-33475c43416e)
which is unresponsive to fingerprint input
cancelling the prompt leads to a console error
`Uncaught (in promise) NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

**Comment by skushagra9** [comment]
yes, I am using linux 22.04, and firefox version v122.0 , working fine
