### ISSUE TITLE
Normalize User / Project Id Types

### ISSUE THREAD

**Issue by cstrnt** [uninbox/UnInbox#49]
Currently we have some ids stored as numbers, some as strings (see here for more details: https://github.com/uninbox/UnInbox/issues/49#issuecomment-1925246196)

Those should be normalized so we don't have to do conversions anymore when comparing them.

Also the current conversions should be removed

**Comment by skushagra9** [comment]
should I change it for providers like github, gitlab also ?

**Comment by McPizza0** [comment]
> should I change it for providers like github, gitlab also ?

this is unrelated to the issue

**Comment by skushagra9** [comment]
oh, I see, I was thinking to change the types

**Comment by McPizza0** [comment]
the source of the issue:
when we insert a new db row, the response.insertId is a string so we need to cast it to a number by preceding it with a `+`
throughout the app/db we use number based ids for all internal linking and logic

there **was** an issue where the id column would be returned as a string instead of a number in db queries
so i got into the bad habit of always casting id columns to numbers

the fix: look at all db responses (from DB and from Cache storages), check the type of the returned id and remove the casting if it is no longer needed

a regex search across the codebase `\+.*\.id` shows there are 75 results
each one needs its type checked and the casting to be removed

full testing of the app will need to be conducted after to ensure there arnt any lingering issues

**Comment by skushagra9** [comment]
Thanks, got it

**Comment by skushagra9** [comment]
@McPizza0 , If you aren't working on this issue, can I work on this please ?

**Comment by McPizza0** [comment]
sorry @skushagra9 this issue requires a lot of attention and testing

**Comment by skushagra9** [comment]
Ok
